#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://localhost:3306/dbcobranza?noAccessToProcedureBodies=true
spring.datasource.username=root
spring.datasource.password=$J0n4th4n$
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.show-sql: true

server.max-http-header-size=1KB
server.port=8383